import type { ActivityLog, ApprovalStep, ReportMeta, ReportRow, SummaryCard } from './types';

export const reportMeta: ReportMeta = {
  title: 'Drum Tub Asm 순회 검사 Sheet',
  subtitle: 'Giant-C / AJQ729130',
  documentNo: 'QMS-DRUM-2026-02-28-001',
  lotNo: 'M/Change 시, 1~500EA/2EA · 501~1000EA/3EA',
  model: 'AJQ729130',
  line: '소방설비 조립 1F',
  inspector: '정현수',
  date: '2026.02.28',
  shift: '주간',
  revision: 'Rev. 03',
};

export const summaryCards: SummaryCard[] = [
  {
    id: 'total',
    label: '검사 항목',
    value: '28',
    caption: '전체 체크 포인트',
    tone: 'info',
  },
  {
    id: 'ok',
    label: '정상',
    value: '24',
    caption: '기준 내 확인',
    tone: 'ok',
  },
  {
    id: 'warn',
    label: '주의',
    value: '3',
    caption: '재확인 필요',
    tone: 'warn',
  },
  {
    id: 'empty',
    label: '미입력',
    value: '1',
    caption: '작성 대기',
    tone: 'empty',
  },
];

export const approvalSteps: ApprovalStep[] = [
  {
    label: '작성',
    name: '정현수',
    role: '현장 담당',
    status: 'done',
  },
  {
    label: '검토',
    name: '한남규',
    role: '품질 리더',
    status: 'done',
  },
  {
    label: '승인',
    name: '대기',
    role: '파트장',
    status: 'waiting',
  },
];

export const reportRows: ReportRow[] = [
  {
    id: 'hose-assembly',
    group: '외관 / 구성품',
    item: 'Hose Assembly, Connector',
    spec: ['AEM73412901', '5214ER4001Z', 'MEJ61885422'],
    refs: ['Hose', 'Connector', 'Clamp'],
    values: ['OK', 'OK', 'OK', 'OK'],
    memo: '체결 방향 및 누락 없음',
  },
  {
    id: 'cover-safety',
    group: '외관 / 구성품',
    item: 'Cover, Safety',
    spec: ['MCK67229801', '유 / 무 확인'],
    refs: ['Safety Cover'],
    values: ['유', '유', '유', '유'],
    memo: '스크래치 없음',
  },
  {
    id: 'inlet-bellows',
    group: 'DRUM TUB ASM',
    item: 'Inlet Bellows',
    spec: ['4738ER1004A', '조립 방향 및 씰링 확인'],
    values: ['OK', 'OK', 'OK', 'OK'],
  },
  {
    id: 'tub-cover-gasket',
    group: 'DRUM TUB ASM',
    item: 'Tub Cover Gasket',
    spec: ['4986ER0004L Gray', '4986ER0004P Black', '4986ER0004Q Black'],
    refs: ['Gray', 'Black'],
    values: ['OK', '주의', 'OK', 'OK'],
    memo: '2차 측정품 가스켓 들뜸 재확인',
  },
  {
    id: 'drum-tub-position',
    group: 'DRUM TUB ASM',
    item: 'IP 위치 / Type',
    spec: ['좌측 1P~4P', '우측 1P~4P', '후면 1P~4P'],
    values: ['1P / 2P', '1P / 3P', '2P / 4P', '1P / 4P'],
  },
  {
    id: 'bolt-torque',
    group: 'DRUM TUB ASM',
    item: 'Bolt 체결력',
    spec: ['Cover / Outer', 'T: 80~150 kgf.cm', '자체 관리 90~150'],
    values: ['112', '108', '116', '113'],
    memo: '최소/최대 관리 기준 내',
  },
  {
    id: 'balance-upper',
    group: 'Balance Weight 체결력',
    item: '상부 Balance Weight',
    spec: ['Black L: 7.0kg', '4866ER0007A'],
    values: ['7.0 kg', '7.0 kg', '7.0 kg', '7.0 kg'],
  },
  {
    id: 'balance-lower',
    group: 'Balance Weight 체결력',
    item: '하부 Balance Weight',
    spec: ['Black T: 7.35kg', '4866ER0004A'],
    values: ['7.35 kg', '7.35 kg', '7.35 kg', '7.35 kg'],
  },
  {
    id: 'balance-torque',
    group: 'Balance Weight 체결력',
    item: '체결 토크',
    spec: ['T: 70~120 kgf.cm', '자체 관리 90~150'],
    values: ['104', '102', '110', '105'],
  },
  {
    id: 'stator-torque',
    group: 'STATOR 체결력',
    item: 'Stator Bolt',
    spec: ['AJB73816004', 'AJB73816028', 'AJB73816017 대체 가능'],
    values: ['132', '128', '134', '130'],
  },
  {
    id: 'bearing-pressure-upper',
    group: 'Bearing 압입력 Data',
    item: '상부 압입력',
    spec: ['550~2000 kgf.cm', '4Point 측정'],
    values: ['1018', '1032', '1016', '1028'],
  },
  {
    id: 'bearing-pressure-lower',
    group: 'Bearing 압입력 Data',
    item: '하부 압입력',
    spec: ['550~1900 kgf.cm', '4Point 측정'],
    values: ['986', '1002', '996', '990'],
  },
  {
    id: 'hardness',
    group: '부품 확인',
    item: 'HARDNESS',
    spec: ['6877ER1016', 'N / U / Z / E'],
    values: ['1016 N', '1016 U', '1016 Z', '1016 E'],
  },
  {
    id: 'heater',
    group: '부품 확인',
    item: 'Heater PART NO',
    spec: [
      'AEG33121527 230V/3200W',
      'AEG33121501 120V/1000W',
      'AEG73309903 230V/2000W',
    ],
    values: ['1527', '1501', '9903', '1527'],
    memo: '전압 사양 교차 확인',
  },
  {
    id: 'rotor',
    group: '부품 확인',
    item: 'Rotor',
    spec: ['27AHL72914402-ALB', '신규 사양 적용'],
    values: ['ALB', 'ALB', 'ALB', 'ALB'],
  },
  {
    id: 'gasket-gap',
    group: '치수 / 단차',
    item: 'Gasket 틈새',
    spec: ['3~8mm', '90° 간격 4Point 측정'],
    values: ['4.1 / 4.2', '4.4 / 4.3', '4.1 / 4.0', '4.2 / 4.2'],
  },
  {
    id: 'bearing-step-upper',
    group: '치수 / 단차',
    item: 'Bearing 단차 상부',
    spec: ['0.2mm 이내', '90° 간격 4Point 측정'],
    values: ['0.12', '0.15', '0.11', '0.14'],
  },
  {
    id: 'bearing-step-lower',
    group: '치수 / 단차',
    item: 'Bearing 단차 하부',
    spec: ['1.1~1.5mm', '90° 간격 4Point 측정'],
    values: ['1.21', '1.24', '1.19', '1.22'],
  },
  {
    id: 'siphon',
    group: '특성 검사',
    item: 'Tub Outer Siphon',
    spec: ['Flash, 막힘 없을 것'],
    values: ['OK', 'OK', 'OK', 'OK'],
  },
  {
    id: 'scratch',
    group: '특성 검사',
    item: '제원검사 / 스크래치',
    spec: ['도장 까짐 없음', '외관 스크래치 없을 것'],
    values: ['OK', 'OK', '주의', 'OK'],
    memo: '3차 샘플 후면 미세 스크래치',
  },
  {
    id: 'heater-press',
    group: '특성 검사',
    item: 'Heater 압입 및 Rotor 이물',
    spec: ['Heater 압입 및 Rotor 이물 없을 것', '속 이물 없음'],
    values: ['OK', 'OK', 'OK', 'OK'],
  },
  {
    id: 'leak',
    group: '특성 검사',
    item: '누수 검사',
    spec: ['누수 없을 것', '1회 / 日'],
    values: ['OK', 'OK', 'OK', '미입력'],
  },
  {
    id: 'eco',
    group: '특성 검사',
    item: '친환경검사',
    spec: ['RoHS Mark 부착', 'Lot 식별 가능'],
    values: ['OK', 'OK', 'OK', 'OK'],
  },
  {
    id: 'water-seal',
    group: '특성 검사',
    item: 'Water Seal 압입높이',
    spec: ['0.7±0.3mm', '합격력 15kgf 이상'],
    values: ['0.72 / 16.2', '0.69 / 15.8', '0.74 / 16.0', '0.71 / 15.9'],
  },
  {
    id: 'special-note',
    group: '특이사항',
    item: '특이사항',
    spec: ['라인 특이사항 또는 품질 이슈 기록'],
    values: ['없음', '없음', '가스켓 재확인', '누수 검사 대기'],
    memo: '최종 승인 전 미입력 항목 확인 필요',
  },
];

export const activityLogs: ActivityLog[] = [
  {
    id: 'log-1',
    time: '14:52',
    title: 'Tub Cover Gasket 재확인 요청',
    desc: '2차 샘플에서 들뜸 가능성이 있어 작업자 확인 대기',
    tone: 'warn',
  },
  {
    id: 'log-2',
    time: '14:35',
    title: 'Bearing 압입력 정상 범위 확인',
    desc: '상·하부 압입력 모두 관리 기준 내 입력 완료',
    tone: 'ok',
  },
  {
    id: 'log-3',
    time: '14:10',
    title: '누수 검사 결과 대기',
    desc: '4차 샘플은 설비 대기 후 추가 입력 예정',
    tone: 'empty',
  },
  {
    id: 'log-4',
    time: '13:48',
    title: 'Heater PART NO 교차 확인',
    desc: '사양 혼입 없음, 샘플별 번호 기록 완료',
    tone: 'info',
  },
];

export const sectionAnchors = [
  '외관 / 구성품',
  'DRUM TUB ASM',
  '체결력',
  'Bearing Data',
  '특성 검사',
  '특이사항',
];
